### ISSUE TITLE
Strange standardization happening

### ISSUE THREAD

**Issue by FennerK** [enviPath/enviPath#41]
I wanted to draw a pathway for SMX. I copied the SMILES from http://www.chemspider.com/Chemical-Structure.5138.html (click on "more details")
SMILES: Cc1cc(no1)NS(=O)(=O)c2ccc(cc2)N
If I now do "add new pathway" and copy the SMILES into the molecular editor, it first looks ok. However, when I then hit "submit", the compound that is shown in the pathway has been totally wrongly standardized. Is now suddenly has carbon radicals. Something must be going wrong with standardization when reading a compound into the system.

**Comment by scem** [comment]
After some investigative debugging I came to the conclusion that the reason for this strange behavior is that when the SMILES string is calculated, the implicit Hydrogen number was not evaluated previously.
In Ketcher 2.0.0 smiles.js this is fixed.
Installing ketcher 2.0.0 would certainly fix the problem  - to the cost of it being not usable. The delivery comes with only a part of the resources and a vital part missing.
So instead I just patched ketcher 1.x (1.0.5 beta?).
