### ISSUE TITLE
Missing node label makes pathway inaccessible

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#53]
If something goes wrong and no node label is stored, pathways become inaccessible and so cannot be deleted and are stuck on the system. It should be always possible to access them and delete them, maybe use an empy node label?

```
java.lang.IllegalStateException: Missing node label for https://envipath.org/package/650babc9-9d68-4b73-9332-11972ca26f7b/pathway/897e39ae-799b-47f6-b3ca-3299cb5967c6/node/c0301c46-ae43-487f-8f33-717f14e157d4
        org.kramerlab.pps.api.impl.database.accessors.reviewable.NodeAccesor.getNodeLabel(NodeAccesor.java:70)
        org.kramerlab.pps.api.impl.logic.objects.Node.getNodeLabel(Node.java:220)
        org.kramerlab.pps.api.impl.database.accessors.reviewable.PathwayAccessor.loadMap(PathwayAccessor.java:137)
        org.kramerlab.pps.api.impl.logic.objects.Pathway.loadMap(Pathway.java:262)
        org.kramerlab.pps.api.impl.logic.objects.Pathway.edgeSet(Pathway.java:493)
```

**Comment by lorsbach** [comment]
Replacing the IllegalStateException with:
`return new CompoundStructure(FormatConverter.fromSmiles(""));` 
will result in an ConversionException when displaying the Pathway. 
However the getting the pathway out of the DB works and a delete on this pathway succeeds without an exception.
