### ISSUE TITLE
delete pathway node destroys pathway

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#69]
a pathway is not displayed anymore after deleting a node. An exception is thrown at delete/

**Comment by steven-lang** [comment]
I could not reproduce the exception. I've created a pathway with two random compounds and deleted one of them afterwards. Everything was fine. Please specify further

**Comment by joergwicker** [comment]
https://envipath.org/package/650babc9-9d68-4b73-9332-11972ca26f7b/pathway/82da041d-b7f7-41ba-951a-313b92638398
is an example
