### ISSUE TITLE
limnode and limdepth cannot be modified

### ISSUE THREAD

**Issue by scem** [enviPath/enviPath#70]
When defining settings, there is no (or no obvious) way to modify the values for limnode and limdepth.
One can remove them altogether but not change.

**Comment by joergwicker** [comment]
You can remove them and add new limnode and limdepth.

**Comment by scem** [comment]
Ok. But how? It's either hidden or I'm too blind to see.

**Comment by joergwicker** [comment]
New Setting, page 3, Select truncator, choose Limited Depth/Node, enter number, click add, next, submit.
