### ISSUE TITLE
Threshold in settings is not shown in all browsers

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#79]
In firefox seems to work (the  cutoff below the model), in other browsers this is not there

**Comment by steven-lang** [comment]
Works for me, tested on:
- Chromium 53.0.2785.143 
- Mozilla Firefox 49.0.1
- conkeror 1.0.3
- Midori 0.5.11
- Opera 40.0.2308.90

Cut-off is now enabled (cba29e8)
