### ISSUE TITLE
Problems with scenario filling

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#83]
If I go under „Scenarios“ > „Actions“ > „Add full scenario“, I can fill out the different parameters (comments see later tickets), but if I want to submit the scenario this does not work. This is even the case if all fields are filled with a value. If I don’t fill all fields, I additionally get a “Input missing” message. However, it should be possible that one does not need to fill in all fields. In fact, in a lot of the DAR soil scenarios not all fields are filled.

**Comment by steven-lang** [comment]
I could not reproduce this issue. I've successfully created a [soil scenario](https://envipath.org/package/650babc9-9d68-4b73-9332-11972ca26f7b/scenario/361bde6f-98be-4ee4-b33a-1cd5dba34e8b) with only _microbial mass_ info set and a [sludge scenario](https://envipath.org/package/650babc9-9d68-4b73-9332-11972ca26f7b/scenario/ba352b31-fcd3-40f1-b2c2-766adbfd3c35) with only _type of aeration_ set. Posting partial scenarios has already worked before.
