### ISSUE TITLE
Enable mouse-over comments for scenario entries

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#84]
Each addinfo will get a comment, a mouse-over on the entry should display the comment.

**Comment by steven-lang** [comment]
At which point? While creating a new scenario in the modal (/scenario) or in the scenario-content (/scenario/id)?

**Comment by joergwicker** [comment]
Both.

**Comment by steven-lang** [comment]
Technically implemented. The comments/descriptions need to be added in the method _getMouseOverText_ of each additional information.
