### ISSUE TITLE
Minor changes in scenario

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#89]
- [x] “original amount of sludge”
- should be renamed to  “initial amount of sludge in bioreactor”
- [x] “additional parameters measured”
- it needs to be possible to also check multiple options
- Super- and subscripts should be used as: NH4+, NO3-, NO2-, NH4-, Ntot, Ptot, PO43-,DOC, none
- “Oxygen uptake rate (OUR)” and “ammonia uptake rate (AUR)” should be added
- There should also be an option for the user to add additional parameters not listed
- [x] “solvent for compound solution”
- There should also be an option for the user to add solvents not listed, including free text such as “Methanol: Water, 1:9”
- [x] “Total suspended solids”
- The abbreviation is “TSS” not TTS.
- It should be renamed to “total suspended solids concentration”?
- [x] For “Volatile suspended solids”
- The abbreviation is “VSS” instead of TTS
- It should be renamed to “volatile suspended solids concentration”
- [x] For “type of addition”
- Should be renamed to “type of compound addition”
- [x] For “Organic content”
- Should be renamed to “Organic content of sludge”
- [x] For “Redox condition”
- There should also be an option for the user to add redox conditions not listed

**Comment by steven-lang** [comment]
Shall _Oxygen uptake rate (OUR)_ and _Ammonia uptake rate_ be a choice in the _additional parameters measured_ or each an own additional information?
