### ISSUE TITLE
Sludge scenario mask

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#94]
The original list of parameters we sent had a specific order, which is now off. However, this order should be re-stored because it helps a lot for the users to understand what is actually meant by the parameters. Ideally, there would even be a few subheadings under which they are ordered (see below for suggestions). 
General study information:

- Name
- Description
- Date
- Reference

Sludge source:

- Inoculum source
- Sludge retention time

Experimental conditions:

- Bioreactor 
- Original amount of sludge
- Source of liquid matrix
- Type of aeration
- Addition of nutrients
- Organic content (value and dimension, OM or OC)
- CEC
- Total suspended solids concentration
- Volatile suspended solids concentration
- Redox condition
- Temperature
- Acidity, pH
- Additional parameters measured

Compound addition:

- Final compound concentration
- Type of addition
- Solvent for compound solution

**Comment by joergwicker** [comment]
“Source of liquid matrix” is currently missing completely and should be added

**Comment by steven-lang** [comment]
Are there any further descriptions for "Source of liquid matrix"?
