### ISSUE TITLE
Malformed UTF-8  character in JSON string on compounds

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#98]
Malformed UTF-8 character in JSON string at:
- https://envipath.org/package/3929925e-b71c-4c92-bc59-281a0b595cd2/compound/55a40171-5d5d-44e6-8bd1-0322fabb2c76
- https://envipath.org/package/3929925e-b71c-4c92-bc59-281a0b595cd2/compound/df936535-9854-4cfb-9c60-d6bd3637f4bb
- https://envipath.org/package/3929925e-b71c-4c92-bc59-281a0b595cd2/compound/19a60c37-c47a-4f33-a37f-0c61cb6a5671
- https://envipath.org/package/3929925e-b71c-4c92-bc59-281a0b595cd2/compound/5a69680c-718e-400d-ba90-cce08e7e6f3f
- https://envipath.org/package/3929925e-b71c-4c92-bc59-281a0b595cd2/compound/478c1208-6c05-417c-be3a-86dd72624379

**Comment by steven-lang** [comment]
Fixed ded2178dadcbf0a204680aa4099f1f708ace2e24
